export const HELLO: string = 'HELLO'
export const REGISTER: string = 'REGISTER'
export const CREATE_ROOM: string = 'CREATE_ROOM'
export const GET_ROOM: string = 'GET_ROOM'
export const JOIN_ROOM: string = 'JOIN_ROOM'
export const NEW_USER: string = 'NEW_USER'
export const USER_LEFT: string = 'USER_LEFT'
export const OWNER_LEFT: string = 'OWNER_LEFT'
export const START_GAME: string = 'START_GAME'
export const CURRENT_PLAYER: string = 'CURRENT_PLAYER'
export const CURRENT_WORD: string = 'CURRENT_WORD'
export const TIMER: string = 'TIMER'
export const CURRENT_ROUND: string = 'CURRENT_ROUND'
export const DRAWING: string = 'DRAWING'
export const CURRENT_PLAYERS: string = 'CURRENT_PLAYERS'
export const NEW_MESSAGE: string = 'NEW_MESSAGE'
export const GUESSED: string = 'GUESSED'
export const PLAYERS: string = 'PLAYERS'

export const ROUND_START: string = 'ROUND_START'
export const ROUND_END: string = 'ROUND_END'
export const WORD_PICK: string = 'WORD_PICK'
export const WORD_SELECT: string = 'WORD_SELECT'

export const GAME_END: string = 'GAME_END'
